Repository Rudy-Menjivar/git-shopping, pull requests merged in 2021-01, with the labels that each got.

#1 test
  README.md
Labels: enhancement

#2 Html
  public/main.html
  public/members.html
  public/signup.html
  public/stylesheets/style.css
Labels: enhancement

#9 Included api cart within nav and added api cart first clothing item
  public/main.html
Labels: enhancement

#7 included several images to link with shirt items
  public/assets/images/HanHent Funny Programming T Shirt Male Cotton.jpg
  public/assets/images/Only-5-Decades-Old-Printed-Customized-Tshirt-50th-Birthday.jpg
  public/assets/images/Read This Out Loud!.jpg
  public/assets/images/Why You Delete Cookies.jpg
  public/assets/images/clshirt1613.jpg
Labels: enhancement

#31 added main.handlebars
  views/layouts/main.handlebars
Labels: enhancement

#33 Included popper support for bs 4.0, and updated bs 4.0 script links
  views/layouts/main.handlebars
Labels: bug

#34 Navbar
  public/members.html
  public/signup.html
Labels: bug

#38 test
  README.md
Labels: documentation

#44 Login hbs
  views/index.handlebars
  views/login.handlebars
  views/register.handlebars
Labels: enhancement

#43 created login and register handlebar pages
  views/index.handlebars
  views/register.handlebars
Labels: enhancement

#45 eliminated all single quotes and pluralize member
  controllers/gsController.js
Labels: bug

#46 updated to get rid of travis-ci build errors
  server.js
Labels: bug

#50 Controller lint upd
  controllers/gsController.js
  views/members.handlebars
  views/register-success.handlebars
Labels: bug

#48 members handlebars created
  views/members.handlebars
Labels: good first issue

#47 Server update
  server.js
Labels: bug

#51 Corrected all lint errors but disabling some that aren't necessary
  models/db.js
Labels: bug

#52 Applied nav link updates, login layout and cart moved to body
  views/index.handlebars
  views/login.handlebars
  views/members.handlebars
  views/register-success.handlebars
  views/register.handlebars
Labels: bug

#56 added clothing handlebars
  views/clothing.handlebars
Labels: good first issue

#60 added items to page
  views/index.handlebars
Labels: enhancement

#66 changed font
  public/stylesheets/style.css
  views/clothing.handlebars
  views/shoes.handlebars
Labels: bug

#71 corrected prices and descriptions, cleaned up front end
  public/stylesheets/style.css
  views/clothing.handlebars
  views/index.handlebars
  views/shoes.handlebars
Labels: bug

#81 corrected api button src links
  views/members.handlebars
Labels: bug

#82 moved apicartAPI script to main.handlebars
  views/layouts/main.handlebars
  views/members.handlebars
Labels: enhancement

#83 removed extra blank lines and moved heading so items line up correctly
  views/index.handlebars
  views/register.handlebars
Labels: bug

#88 removed apicart, linking buttons to members page with updated styling
  public/stylesheets/style.css
  views/index.handlebars
Labels: bug

#93 Updated layouts and added login req to access clothes and shoes hbs p…
  controllers/gsController2.js
  views/clothing.handlebars
  views/shoes.handlebars
Labels: enhancement
